### ISSUE TITLE
can't install cumm on agx xavier 

### ISSUE THREAD

**Issue by odroidodroid** [FindDefinition/cumm#13]
jetpack 5.0.1
cuda-11.4
python3.8

I failed to install cumm.. from 0.3.0 to 0.3.4 version all failed
so I tried to compile libcufilt.a (edg_decode) with g++ and nvcc with -fPIC, succeed
but after recompiling, the error did not disappear

export CUMM_DISABLE_JIT="1"
export CUMM_ARCH_LIST="7.2+PTX"
sudo pip install -e .

[39/39] [GCC][Link]/home/jetson/cumm/build/temp.linux-aarch64-cpython-38/cumm/build/core_cc/core_cc.cpython-38-aarch64-linux-gnu.so
FAILED: /home/jetson/cumm/build/temp.linux-aarch64-cpython-38/cumm/build/core_cc/core_cc.cpython-38-aarch64-linux-gnu.so 
g++ @/home/jetson/cumm/build/temp.linux-aarch64-cpython-38/cumm/build/core_cc/core_cc.cpython-38-aarch64-linux-gnu.so.rsp -lcudart -lnvrtc -lcufilt -ldl -L "/usr/local/cuda/lib64" -L "/usr/local/cuda/lib64" -Wl,--no-as-needed -lnvrtc-builtins -shared -o /home/jetson/cumm/build/temp.linux-aarch64-cpython-38/cumm/build/core_cc/core_cc.cpython-38-aarch64-linux-gnu.so
**/usr/bin/ld: /usr/local/cuda/lib64/libcufilt.a(edg_decode.o): relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `stderr@@GLIBC_2.17' which may bind externally can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/cuda/lib64/libcufilt.a(edg_decode.o)(.text._Z6getoptiPKPcPKc+0x15c): unresolvable R_AARCH64_ADR_PREL_PG_HI21 relocation against symbol `stderr@@GLIBC_2.17'**
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.

**Comment by FindDefinition** [comment]
should be fixed in newest commit, you can have a try.

**Comment by odroidodroid** [comment]
Thank you!
