### ISSUE TITLE
Install cumm on Orin

### ISSUE THREAD

**Issue by Siyeong-Lee** [FindDefinition/cumm#15]
Similar to the previous issue (https://github.com/FindDefinition/cumm/issues/13) , I also failed to install `cumm` on Orin. 

Can you tell me how to install it on Orin? Any comments would be highly appreciated.

The options I have set are as follows:
```
export CUMM_DISABLE_JIT="1"
export CUMM_ARCH_LIST="8.7+PTX"
sudo pip install -e.
```
----
* The error message is:
[39/39] [GCC][Link]/home/siyeong/workspace/cumm/build/temp.linux-aarch64-cpython-38/cumm/build/core_cc/core_cc.cpython-38-aarch64-linux-gnu.so
    FAILED: /home/siyeong/workspace/cumm/build/temp.linux-aarch64-cpython-38/cumm/build/core_cc/core_cc.cpython-38-aarch64-linux-gnu.so
    g++ @/home/siyeong/workspace/cumm/build/temp.linux-aarch64-cpython-38/cumm/build/core_cc/core_cc.cpython-38-aarch64-linux-gnu.so.rsp -lcudart -lnvrtc -lcufilt -ldl -L "/usr/local/cuda/lib64" -L "/usr/local/cuda/lib64" -Wl,--no-as-needed -lnvrtc-builtins -shared -o /home/siyeong/workspace/cumm/build/temp.linux-aarch64-cpython-38/cumm/build/core_cc/core_cc.cpython-38-aarch64-linux-gnu.so
    /usr/bin/ld: /usr/local/cuda/lib64/libcufilt.a(decode.o): relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `display_func_params' which may bind externally can not be used when making a shared object; recompile with -fPIC
    /usr/local/cuda/lib64/libcufilt.a(decode.o): in function `demangle_bare_function_type(char const*, int, int, a_decode_control_block*)':
 /dvs/p4/build/sw/rel/gpgpu/toolkit/r11.4/compiler/drivers/compiler/edg/EDG_6.2/src/../util/decode.c:4996:(.text._ZL27demangle_bare_function_typePKciiP22a_decode_control_block+0x53c): dangerous relocation: unsupported relocation
    /usr/bin/ld: /usr/local/cuda/lib64/libcufilt.a(decode.o): relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `display_func_params' which may bind externally can not be used when making a shared object; recompile with -fPIC
    /usr/local/cuda/lib64/libcufilt.a(decode.o): in function `decode_identifier(char const*, char*, unsigned long, int*, int*, unsigned long*)':
    /dvs/p4/build/sw/rel/gpgpu/toolkit/r11.4/compiler/drivers/compiler/edg/EDG_6.2/src/../util/decode.c:8766:(.text._Z17decode_identifierPKcPcmPiS2_Pm+0x24): dangerous relocation: unsupported relocation
    /tmp/pip-build-env-mjzpnmvl/overlay/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    /tmp/pip-build-env-mjzpnmvl/overlay/lib/python3.8/site-packages/pkg_resources/__init__.py:123: PkgResourcesDeprecationWarning: 0.1.36ubuntu1 is an invalid version and will not be supported in a future release

**Comment by FindDefinition** [comment]
1. CUMM_ARCH_LIST should be ```8.7+PTX``` for orin. this environment only valid for spconv, build cumm don't need this 
2. ```libcufilt``` problem should be fixed in cumm newest commit (master branch, hasn't released to tags yet), which commit do you use for orin?

**Comment by Siyeong-Lee** [comment]
1. Sorry. I wrote it wrong. I set `CUMM_ARCH_LIST` to "8.7+PTX".
2. Thank you!

**Comment by Siyeong-Lee** [comment]
The issue is closed, but I'm leaving a reply for others.

After applying the commit, the build was done successfully.
I also succeeded in installing spconv. Thank you again.
